<script lang="ts">
	import Seo from '#lib/components/site/Seo.svelte';
	import { REPO_URL } from '#lib/site.js';
</script>

<Seo
	title="About — Emergency Care System"
	description="What this demo is, what it isn't, and how its source repository is organized."
	path="/about/"
/>

<section class="page-hero">
	<h1>About this project</h1>
	<p>
		This is a public, free, open-source demonstration of how to plan an emergency care system,
		from higher-level use cases to lower-level test automation.
	</p>
</section>

<div class="notice">
	<strong>Synthetic data only.</strong> All patient names, staff names, vitals, timestamps, and
	metrics anywhere in this project — the app, the specs, and the tests — are fictitious and
	generated by Claude AI, for educational purposes. This is not a real emergency care system and
	was not built from any real hospital's data or workflows.
</div>

<div class="card-grid">
	<div class="card">
		<h2>Specification-driven</h2>
		<p>
			Every feature starts as a Gherkin <code>.feature</code> file in
			<code>tests-with-given-when-then-features/</code>
			— the single source of truth that every app screen and every test suite is built to match.
		</p>
	</div>

	<div class="card">
		<h2>The app</h2>
		<p>
			<code>src/</code> is a real SvelteKit 5 app implementing all 22 features as a single-page
			dashboard, styled with
			<a href="https://www.npmjs.com/package/lily-design-system-svelte-headless"
				>Lily Design System</a
			>
			and <a href="https://www.npmjs.com/package/@svar-ui/svelte-grid">SVAR Svelte</a>
			components. There's no real backend — all data is seeded at load time and, where a scenario
			needs it to survive a page reload (such as duplicate-patient detection), persisted to
			<code>localStorage</code> only, in that one browser. Sign in with any free-text identity —
			a role phrase like "a registration clerk" or a name like "Dr. Smith" — or with
			<code>doctor@example.com</code>, <code>nurse@example.com</code>, or
			<code>administrator@example.com</code> (password <code>secret</code>).
		</p>
	</div>

	<div class="card">
		<h2>The tests</h2>
		<p>
			The same 171 scenarios are ported one-to-one across twelve suites, pairing two automation
			libraries (Selenium, Playwright) with six languages (JavaScript, TypeScript, Python, C#,
			Java, Rust).
			See <a href="/testing/">Testing</a> for details.
		</p>
	</div>

	<div class="card">
		<h2>Skills</h2>
		<p>
			<code>skills/</code> in the source repository packages some of the conventions this project
			follows (Selenium/JavaScript test-writing, Lily Design System usage) as reusable Claude Code
			skills.
		</p>
	</div>
</div>

<p>Everything is in one repository: <a href={REPO_URL}>{REPO_URL}</a>.</p>
