<script lang="ts">
	import Seo from '#lib/components/site/Seo.svelte';
	import { REPO_URL } from '#lib/site.js';
</script>

<Seo
	title="Emergency Care System"
	description="A public, free, open-source demonstration of how to plan an emergency care system, from higher-level use cases to lower-level test automation."
	path="/"
/>

<section class="page-hero">
	<span class="badge">Demo · synthetic data</span>
	<h1>Emergency care system</h1>
	<p>
		A public, free, open-source demonstration of how to plan an emergency care system, from
		higher-level use cases to lower-level test automation. All of the information in the demo is
		synthetic and generated by Claude AI, for educational purposes. This is not a real emergency
		care system.
	</p>
</section>

<div class="card-grid">
	<div class="card">
		<h2>22 features</h2>
		<p>
			Every feature starts as a Gherkin <code>.feature</code> file (As a… I want… So that…, with
			a Background and several scenarios), covering registration, triage, bed management, orders,
			labs, medications, discharge, dashboards, mass-casualty and code-blue response,
			authentication, and audit trails.
		</p>
		<p><a href="/features/">Browse all 22 features →</a></p>
	</div>

	<div class="card">
		<h2>Twelve test suites, one contract</h2>
		<p>
			The same 171 scenarios are ported one-to-one across Selenium and Playwright, in
			JavaScript, TypeScript, Python, C#, Java, and Rust — twelve suites total, all driving the
			same running SvelteKit app through its <code>data-testid</code> attributes.
		</p>
		<p><a href="/testing/">How the test suites work →</a></p>
	</div>

	<div class="card">
		<h2>A real running app</h2>
		<p>
			<code>src/</code> in the source repository is a real SvelteKit 5 app implementing all 22
			features as a single-page dashboard, styled with the Lily Design System. There's no real
			backend — all data is fictitious and, where a scenario needs it to survive a reload, kept
			in <code>localStorage</code> only, in that one browser.
		</p>
		<p><a href="/about/">More about this project →</a></p>
	</div>

	<div class="card">
		<h2>Source</h2>
		<p>
			Everything here — the app, the specs, the skills, and all twelve test suites — lives in one
			public repository.
		</p>
		<p><a href={REPO_URL}>{REPO_URL}</a></p>
	</div>
</div>
